platform: linux
image_resource:
  type: docker-image
  source:
    repository: czero/rootfs
inputs:
- name: ami
- name: stock-ami
- name: stemcell
- name: brkt-pcf-pipelines
outputs:
- name: brktized-stemcell
params:
  REGION:
run:
  path: brkt-pcf-pipelines/tasks/package-stemcell/task.sh
