platform: linux
image_resource:
  type: docker-image
  source:
    repository: czero/rootfs
inputs:
  - name: brkt-pcf-pipelines
params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  REGION:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  PEM:
run:
  path: brkt-pcf-pipelines/tasks/bump-opsmanager-disk-size/task.sh