groups: []
resources:
- name: pcf-pipelines
  type: git
  source:
    uri: git@github.com:pivotal-cf/pcf-pipelines.git
    branch: master
    tag_filter: v0.23.0
    private_key: {{git_private_key}}
- name: brkt-pcf-pipelines
  type: git
  source:
    branch: master
    private_key: {{git_private_key}}
    uri: git@github.com:olle-brkt/brkt-pcf-pipelines.git
- name: patched-pipeline
  type: s3
  source:
    access_key_id: {{aws_access_key_id}}
    secret_access_key: {{aws_secret_access_key}}
    bucket: {{patched_pipeline_s3_bucket}}
    disable_ssl: false
    endpoint: {{s3_endpoint}}
    region_name: {{aws_region}}
    versioned_file: pipeline.yml
resource_types: []
jobs:
- name: create-initial-state
  plan:
  - aggregate:
    - get: brkt-pcf-pipelines
  - task: create-initial-state
    file: brkt-pcf-pipelines/tasks/create-initial-state/task.yml
    params:
      AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
      S3_BUCKET_TERRAFORM: {{terraform_state_s3_bucket}}
      S3_BUCKET_PATCHED_PIPELINE: {{patched_pipeline_s3_bucket}}
      S3_ENDPOINT: {{s3_endpoint}}
      S3_REGION: {{aws_region}}
- name: patch-pipeline
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: brkt-pcf-pipelines
    - get: patched-pipeline
  - task: patch-pipeline
    file: brkt-pcf-pipelines/tasks/patch-pipeline/task.yml
    params:
      ATC_EXTERNAL_URL: {{concourse_url}}
  - put: patched-pipeline
    params:
      file: generated-pipeline/pipeline.yml
- name: set-pipeline
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: brkt-pcf-pipelines
    - get: patched-pipeline
      passed:
      - patch-pipeline
      trigger: true
  - task: set-pipeline
    file: brkt-pcf-pipelines/tasks/set-pipeline/task.yml
    params:
      PEM: {{PEM}}
      git_private_key: {{git_private_key}}
      pipeline_name: {{pipeline_name}}
      concourse_url: {{concourse_url}}
      basic_auth_username: {{basic_auth_username}}
      basic_auth_password: {{basic_auth_password}}
      team_name: {{team_name}}
      patched_pipeline_s3_bucket: {{patched_pipeline_s3_bucket}}
      pipeline_params: {{pipeline_params}}
