platform: linux
image_resource:
  type: docker-image
  source:
    repository: czero/rootfs
inputs:
  - name: brkt-pcf-pipelines
  - name: brktized-stemcell
params:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPSMAN_USR:
  OPSMAN_PWD:
  PIVNET_API_TOKEN:
  PEM:
run:
  path: brkt-pcf-pipelines/tasks/upload-stemcell/task.sh