platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/rootfs

inputs:
- name: brkt-pcf-pipelines

params:
  S3_BUCKET_TERRAFORM:
  S3_BUCKET_PATCHED_PIPELINE:
  S3_BUCKET_ENCRYPTED_AMIS:
  S3_ENDPOINT:
  S3_REGION:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:

run:
  path: brkt-pcf-pipelines/tasks/create-initial-state/task.sh
