platform: linux
image_resource:
  type: docker-image
  source:
    repository: czero/rootfs
inputs:
- name: pivnet-product
- name: brkt-pcf-pipelines
outputs:
- name: stock-ami
- name: stemcell
params:
  IAAS:
  REGION:
  PIVNET_API_TOKEN:
run:
  path: brkt-pcf-pipelines/tasks/find-stock-stemcell-ami/task.sh