platform: linux
image_resource:
  type: docker-image
  source:
    repository: python
    tag: 2.7.13-wheezy
inputs:
- name: brkt-pcf-pipelines
- name: encrypted-amis
outputs:
- name: results
params:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPSMAN_CLIENT_ID:
  OPSMAN_CLIENT_SECRET:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  PIVNET_API_TOKEN:
  NO_PROXY:
  OM_IP:
  IAAS:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  REGION:
  URL:
  EMAIL:
  PASSWORD:
  METAVISOR_VERSION:
run:
  path: brkt-pcf-pipelines/tasks/encrypt-director/task.sh